"""
Reporter Agent — Generates final documentation and project report.
"""
import json
from backend.agents.base_agent import BaseAgent
from backend.tools.file_tool import FileTool


REPORTER_SYSTEM_PROMPT = """You are a technical writer at "The Forge".
Generate comprehensive project documentation.

## Output a README.md that includes:
1. Project name and description
2. Tech stack used
3. How to install and run the project
4. Project structure overview
5. API endpoints (if applicable)
6. Environment variables needed
7. Features list

Write in clean Markdown. Be thorough and professional.
"""


class ReporterAgent(BaseAgent):
    role = "reporter"
    description = "Reporter — generates documentation and project reports"

    async def execute(self, state: dict) -> dict:
        workspace_path = state.get("workspace_path", "")
        requirements = state.get("requirements", {})
        blueprint = state.get("blueprint", {})
        generated_files = state.get("generated_files", {})
        qa_report = state.get("qa_report", {})

        if not workspace_path:
            return {
                **self._log(state, "ERROR", "No workspace path!", "error"),
                "current_phase": "error",
            }

        file_tool = FileTool(workspace_path)

        # Build context for documentation
        file_list = "\n".join(f"- {path}" for path in generated_files.keys())

        prompt = f"""Generate a professional README.md for this project:

## Requirements:
{json.dumps(requirements, indent=2)}

## Architecture:
{blueprint.get('architecture_notes', 'N/A')}

## Files:
{file_list}

## API Routes:
{json.dumps(blueprint.get('api_routes', []), indent=2)}

## QA Results:
Tests Run: {qa_report.get('tests_run', 0)}
Tests Passed: {qa_report.get('tests_passed', 0)}
Overall: {'PASS' if qa_report.get('overall_pass', False) else 'NEEDS REVIEW'}

## Project Tree:
{file_tool.get_project_tree()}
"""

        readme = await self.call_model(
            system_prompt=REPORTER_SYSTEM_PROMPT,
            user_prompt=prompt,
        )

        if readme:
            file_tool.write_file("README.md", readme, force=True)
            generated_files["README.md"] = readme

        # Generate a technical report
        report = f"""# Project Report: {requirements.get('name', 'Unknown')}

## Summary
- **Type**: {requirements.get('project_type', 'N/A')}
- **Features**: {len(requirements.get('features', []))}
- **Files Generated**: {len(generated_files)}
- **QA Status**: {'✅ PASS' if qa_report.get('overall_pass', False) else '⚠️ NEEDS REVIEW'}

## Tech Stack
{json.dumps(requirements.get('tech_stack', {}), indent=2)}

## Files
{file_list}

## Workspace Location
`{workspace_path}`

---
*Generated by The Forge AI*
"""
        file_tool.write_file("REPORT.md", report, force=True)

        return {
            **self._log(state, "Documentation generated", "README.md and REPORT.md created", "success"),
            "generated_files": generated_files,
            "final_report": report,
            "current_phase": "complete",
            "is_complete": True,
        }
